export const ON_LOGOUT_FRONT_COVER = "ON_LOGOUT_FRONT_COVER"; //Front cover
export const UPDATE_FRONT_COVER = "UPDATE_FRONT_COVER"; //Front cover
export const GET_FRONT_COVER = "GET_FRONT_COVER"; //Front cover
export const UPDATE_COVER_LOGO = "UPDATE_COVER_LOGO"; //Front cover
export const UPDATE_COVER_TITLE = "UPDATE_COVER_TITLE"; //Front cover
export const UPDATE_COVER_COMMENT_SEC = "UPDATE_COVER_COMMENT_SEC"; //Front cover
export const UPDATE_COVER_BG_IMG = "UPDATE_COVER_BG_IMG"; //Front cover
export const UPDATE_COVER_BG_COLOR = "UPDATE_COVER_BG_COLOR"; //Front cover
export const GET_DEFAULT_BG_IMAGES = "GET_DEFAULT_BG_IMAGES"; //Front cover

export const GET_METRICS = "GET_METRICS"; //Metrics
export const ADD_NEW_METRIC = "ADD_NEW_METRIC"; //Metrics
export const UPDATE_METRIC = "UPDATE_METRIC"; //Metrics

export const GENERATE_COVERAGE = "GENERATE_COVERAGE"; //Coverage
export const UPDATE_COVERAGE_TITLE = "UPDATE_COVERAGE_TITLE"; //Coverage
// export const TAKING_SCREEN_SHOTS = "TAKING_SCREEN_SHOTS"; //Coverage
// export const UPDATE_COVERAGE_REDUCER = "UPDATE_COVERAGE_REDUCER"; //Coverage
export const UPDATE_SCREENSHOTS_DATA = "UPDATE_SCREENSHOTS_DATA"; //Coverage
export const UPDATE_SINGLE_SCREENSHOT = "UPDATE_SINGLE_SCREENSHOT"; //Coverage

export const GET_ALL_COVERBOOKS = "GET_ALL_COVERBOOKS"; //Coverage
export const GET_CREATED_COVER_ID = "GET_CREATED_COVER_ID"; //Coverage
export const RESET_CREATED_COVER_ID = "RESET_CREATED_COVER_ID"; //Coverage
export const DELETE_MULTIPLE_COVERS = "DELETE_MULTIPLE_COVERS"; //Coverage
export const FETCH_BOOKS = "FETCH_BOOKS"; //Coverage


// Auth
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTH_API_ERROR = "AUTH_API_ERROR";
export const IS_API_CALL = "IS_API_CALL";
export const FORGET_PASSWORD = "FORGET_PASSWORD";

// UPDATE PROFILE
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_USER_PLAN_ID = "UPDATE_USER_PLAN_ID";

// GET ALL SUBSCRIPTIONS
export const GET_ALL_SUBSCRIPTIONS = "GET_ALL_SUBSCRIPTIONS";


// VERIFICATION INVITED USER
export const GET_INVITED_USER_EMAIL = "GET_INVITED_USER_EMAIL";
// TEAM MEMBERS
export const GET_ALL_TEAM_MEMBERS = "GET_ALL_TEAM_MEMBERS";

// FOLDERS
export const GET_ALL_FOLDERS = "GET_ALL_FOLDERS";

